feat: Basic agent table component
chatwoot/design pull request #11
Opened 2024-02-15 10:22 UTC by iamsivin

**Screenshot**

<img width="1198" alt="image" src="https://github.com/chatwoot/design/assets/64252451/2fbf974b-f385-4ac2-93ad-96c8114be600">

2024-02-16 01:45 UTC, pranavrajs commented on src/components/Table/Table.story.vue
> +    open_conversations: 3,
Let us not use underscore.

2024-02-16 01:45 UTC, pranavrajs commented on src/components/Table/Table.vue
> +import { useVueTable, FlexRender, getCoreRowModel } from '@tanstack/vue-table';
I would keep imports at the top.

2024-02-16 01:46 UTC, pranavrajs commented on src/components/Table/Table.story.vue
> +    <Variant title="AgentTable">
```suggestion
    <Variant title="User list">
```

2024-02-16 01:46 UTC, pranavrajs commented on src/components/Table/Table.story.vue
> +  <Story title="Table/AgentTable" width="100%">
```suggestion
  <Story title="Table/UserList" width="100%">
```

2024-02-16 01:46 UTC, pranavrajs commented on src/components/Table/Table.vue
> +<style></style>
Unnecessary style

2024-02-16 01:48 UTC, pranavrajs commented on src/components/Table/components/AgentSection.vue
> +<template>
I would rename this file something more generic like UserCard or something of that sort.

2024-02-16 01:48 UTC, pranavrajs requested changes
Minor comments, otherwise looks good.

2024-02-16 01:49 UTC, pranavrajs commented
@iamsivin Can you please include pagination as well into the component? We don't need to handle those in the dashboard code separately.

2024-02-16 02:41 UTC, iamsivin commented
> @iamsivin Can you please include pagination as well into the component? We don't need to handle those in the dashboard code separately.

Sure will add it.

2024-02-16 18:15 UTC, iamsivin commented
> @iamsivin Can you please include pagination as well into the component? We don't need to handle those in the dashboard code separately.

@pranavrajs Done https://github.com/chatwoot/design/pull/11/commits/f8eb38afaae72ee02786e066f9c157424bd21f94

2024-02-21 01:10 UTC, pranavrajs commented on src/components/Table/components/UserCard.vue
> +      alt="Profile picture"
Let us use "name + profile picture"

2024-02-21 02:46 UTC, iamsivin commented on src/components/Table/components/UserCard.vue
> +      alt="Profile picture"
@pranavrajs Done https://github.com/chatwoot/design/pull/11/commits/1c3e3344ee744d644ac2cb776e13d554a5daf3ca

2024-02-21 04:07 UTC, pranavrajs approved these changes

2024-02-21 04:08 UTC, merged